### PR TITLE
#171080781 fixes token social auth frontend

### PR DESCRIPTION
**Pull request by gildniy**
#### What does this PR do?
Checks if the user token was provided to log in the user and fixes the responsiveness of the buttons
#### Description of Task to be completed?
 - [x]  added a check to see if the user has a valid token not older than 2 secs
 - [x]  fixes some CSS to make the feature responsive through different divices
#### How should this be manually tested?
As this behaves differently on `locahost` and `live host`, a test app was created and hosted on Heroku to show the feature in live mode, on this [link](https://boondocks-bn-frontend-test.herokuapp.com/).
 - [x] navigate to `https://boondocks-bn-frontend-test.herokuapp.com/login`
 - [x] click on `Facebook` or `Google` to authenticate using Social Login.
 - [x] once the required logins provided on Facebook or Google website, the user should be redirected back to the websites and get logged in to his profile
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#171080781](https://www.pivotaltracker.com/story/show/171080781)
#### Screenshots (if appropriate)

1. Click on Facebook button
image

2. Fill the logins for Facebook account
image

3. Get redirected to the website and get logged in
image

4. Click on Google button
image

5. Fill the logins for Google account
image

6. Get redirected to the website and get logged in
image

#### Questions:
N/A

### CODE REVIEW

**Comment by Billmike** [comment]
@gildniy resolve conflicts

**Comment by Billmike** [comment]
@gildniy fix merge conflicts

**Comment by RaymondMwaura** [comment]
Resolve conflicts so that it can get merged.

**Comment by Billmike** [comment]
@gildniy fix merge conflicts

**Pull request merged**
