### PR TITLE
#171101785 Fixes inconsistent tables

### PR DESCRIPTION
**Pull request by gildniy**
#### Description of Task to be completed?
- [x] Fixes the table on request search and make it be clickable and access the single request page
- [x] Add pagination on user lists (when the logged-in user has 'super_admin' role)
- [x] Format date on search table to use `time ago` format
#### How should this be manually tested?
- [x] clone the branch
- [x] Login as a super-admin to see the pagination on users lists
- [x] Login as a requester and navigate to the requests page and make a search to see a list of searched requests
- [x] On the searched requests, the user can see formatted `UPDATED` date
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#171101785](https://www.pivotaltracker.com/story/show/171101785)

#### Screenshots (if appropriate)
1. Users list with pagination
image

2. Request search table with formated UPDATED dates
image

#### Questions:
N/A

### CODE REVIEW

**Comment by gildniy** [comment]
> Great work @gildniy, This feature is well implemented. However, there are still inconsistency before and after searching.
> 
> **Before search**
> Screen Shot 2020-02-06 at 12 20 20
> 
> **After search**
> Screen Shot 2020-02-06 at 12 20 55

Now it's fixed.

**Comment by gildniy** [comment]
> Great job so far Gildas. Pagination on the users' list works and the search also returns filtered results. However, when you click on one of the searched results, you are taken to the wrong request page.

Let me check on that!

**Comment by RaymondMwaura** [comment]
The fixes are now good to go. Rebase and we can then merge it.

**Comment by Billmike** [comment]
@gildniy fix conflicts

**Comment by gildniy** [comment]
> The fixes are now good to go. Rebase and we can then merge it.

Fixed.

**Pull request merged**
